Repository OpenFUSIONToolkit/OpenFUSIONToolkit, pull requests merged in 2024-04, with the labels that each got.

#54 TokaMaker: Update l_i calculation to use standard formulation
  src/examples/TokaMaker/DIIID/DIIID_baseline_ex.ipynb
  src/examples/TokaMaker/DIIID/DIIID_mesh.h5
  src/examples/TokaMaker/HBT/HBT_eq_ex.ipynb
  src/examples/TokaMaker/ITER/ITER_baseline_ex.ipynb
  src/examples/TokaMaker/fixed_boundary/fixed_boundary_ex1.ipynb
  src/examples/TokaMaker/fixed_boundary/fixed_boundary_ex2.ipynb
  src/physics/grad_shaf_util.F90
  src/python/OpenFUSIONToolkit/TokaMaker.py
  src/python/wrappers/tokamaker_f.F90
  src/tests/physics/test_TokaMaker.py
Labels: enhancement

#55 Add CUTE example for TokaMaker
  src/docs/doc_tokamaker_main.md
  src/examples/TokaMaker/CMakeLists.txt
  src/examples/TokaMaker/CUTE/CUTE_VDE_ex.ipynb
  src/examples/TokaMaker/CUTE/CUTE_geom.json
  src/examples/TokaMaker/CUTE/CUTE_mesh.h5
  src/examples/TokaMaker/CUTE/CUTE_mesh_ex.ipynb
  src/examples/TokaMaker/DIIID/DIIID_baseline_ex.ipynb
  src/examples/TokaMaker/DIIID/DIIID_mesh_ex.ipynb
  src/examples/TokaMaker/HBT/HBT_eq_ex.ipynb
  src/examples/TokaMaker/HBT/HBT_mesh_ex.ipynb
  src/examples/TokaMaker/ITER/ITER_baseline_ex.ipynb
  src/examples/TokaMaker/ITER/ITER_mesh_ex.ipynb
  src/examples/TokaMaker/fixed_boundary/fixed_boundary_ex1.ipynb
  src/examples/TokaMaker/fixed_boundary/fixed_boundary_ex2.ipynb
  src/ext_libs/bvls.f90
  src/physics/grad_shaf.F90
  src/utilities/generate_doc.py
Labels: documentation, enhancement

#56 ThinCurr: Add support for HODLR compression for L matrix
  src/base/oft_local.F90
  src/bin/thincurr_eig.F90
  src/bin/thincurr_fr.F90
  src/bin/thincurr_td.F90
  src/docs/ThinCurr/doc_thincurr_main.md
  src/docs/ThinCurr/thincurr_example1.md
  src/docs/ThinCurr/thincurr_example2.md
  src/docs/ThinCurr/thincurr_example3.md
  src/docs/ThinCurr/thincurr_example4.md
  src/docs/doc_tokamaker_main.md
  src/docs/images/thincurr_aca_part.png
  src/docs/images/thincurr_aca_scaling.png
  src/docs/images/thincurr_ex4-result.png
  src/examples/ThinCurr/CMakeLists.txt
  src/examples/ThinCurr/ports/oft.in
  src/examples/ThinCurr/ports/oft_in.xml
  src/examples/ThinCurr/ports/thincurr_ex-ports.h5
  src/examples/ThinCurr/ports/thincurr_ex-ports.jou
  src/grid/mesh_local.F90
  src/lin_alg/deriv_matrices.F90
  src/lin_alg/lin_alg_base.F90
  src/lin_alg/native_la.F90
  src/lin_alg/native_solvers.F90
  src/lin_alg/oft_arpack.F90
  src/lin_alg/petsc_la.F90
  src/lin_alg/petsc_solvers.F90
  src/physics/CMakeLists.txt
  src/physics/thin_wall.F90
  src/physics/thin_wall_hodlr.F90
  src/python/OpenFUSIONToolkit/TokaMaker.py
  src/tests/physics/CMakeLists.txt
  src/tests/physics/test_ThinCurr.py
  src/tests/physics/tw_test-cyl.jou
  src/tests/physics/tw_test-cyl_hr.h5
  src/utilities/build_libs.py
  src/utilities/convert_cubit.py
  src/utilities/scripts/ThinCurr_compute_force.py
Labels: documentation, enhancement

#57 Add initial ThinCurr python wrapper/interface
  src/base/oft_io.F90
  src/base/oft_local.F90
  src/base/oft_local_c.c
  src/bin/CMakeLists.txt
  src/bin/thincurr_coupling.F90
  src/bin/thincurr_eig.F90
  src/bin/thincurr_fr.F90
  src/bin/thincurr_from_mode.F90
  src/bin/thincurr_td.F90
  src/docs/ThinCurr/doc_thincurr_main.md
  src/docs/ThinCurr/thincurr_example1.md
  src/docs/ThinCurr/thincurr_example2.md
  src/docs/ThinCurr/thincurr_example3.md
  src/docs/ThinCurr/thincurr_example4.md
  src/examples/ThinCurr/CMakeLists.txt
  src/examples/ThinCurr/REGCOIL/ThinCurr_REGCOIL.ipynb
  src/examples/ThinCurr/REGCOIL/regcoil_out.li383.nc
  src/examples/ThinCurr/plate/plate_eigenvalues.ipynb
  src/examples/ThinCurr/ports/ports_HODLR_eigenvalues.ipynb
  src/examples/ThinCurr/torus/torus_bnorm_mode.ipynb
  src/examples/ThinCurr/torus/torus_freq_response.ipynb
  src/grid/mesh_native.F90
  src/grid/mesh_type.F90
  src/lin_alg/lin_alg_utils.F90
  src/lin_alg/oft_arpack.F90
  src/physics/CMakeLists.txt
  src/physics/thin_wall.F90
  src/physics/thin_wall_hodlr.F90
  src/physics/thin_wall_solvers.F90
  src/python/OpenFUSIONToolkit/CMakeLists.txt
  src/python/OpenFUSIONToolkit/ThinCurr.py
  src/python/OpenFUSIONToolkit/ThinCurr/__init__.py
  src/python/OpenFUSIONToolkit/ThinCurr/_core.py
  src/python/OpenFUSIONToolkit/ThinCurr/_interface.py
  src/python/OpenFUSIONToolkit/ThinCurr/meshing.py
  src/python/OpenFUSIONToolkit/util.py
  src/python/wrappers/CMakeLists.txt
  src/python/wrappers/oft_base_f.F90
  src/python/wrappers/thincurr_f.F90
  src/utilities/generate_doc.py
Labels: documentation, enhancement

#58 TokaMaker: Add functionality to enable support of non-continuous conducting structures
  src/bin/tokamaker_wall.F90
  src/docs/doc_tokamaker_main.md
  src/examples/TokaMaker/CMakeLists.txt
  src/examples/TokaMaker/HBT/HBT_mesh.h5
  src/examples/TokaMaker/HBT/HBT_mesh_ex.ipynb
  src/examples/TokaMaker/LTX/LTX_eq_ex.ipynb
  src/examples/TokaMaker/LTX/LTX_geom.json
  src/examples/TokaMaker/LTX/LTX_mesh.h5
  src/examples/TokaMaker/LTX/LTX_mesh_ex.ipynb
  src/lin_alg/lin_alg_utils.F90
  src/physics/grad_shaf.F90
  src/physics/grad_shaf_td.F90
  src/python/OpenFUSIONToolkit/ThinCurr.py
  src/python/OpenFUSIONToolkit/TokaMaker.py
  src/python/wrappers/tokamaker_f.F90
  src/tests/physics/CMakeLists.txt
  src/tests/physics/LTX_geom.json
  src/tests/physics/test_TokaMaker.py
Labels: documentation, enhancement, tests

#53 Resolved j_BS units normalization, added updated ITER H-mode example
  src/examples/TokaMaker/ITER/ITER_Hmode_ex.ipynb
  src/python/OpenFUSIONToolkit/TokaMaker.py
Labels: documentation, enhancement

#59 TokaMaker: Reorganize python interface and add initial reconstruction capability
  src/bin/tokamaker_gs.F90
  src/bin/tokamaker_wall.F90
  src/docs/doc_tokamaker_main.md
  src/examples/TokaMaker/CUTE/CUTE_VDE_ex.ipynb
  src/examples/TokaMaker/CUTE/CUTE_mesh_ex.ipynb
  src/examples/TokaMaker/DIIID/DIIID_baseline_ex.ipynb
  src/examples/TokaMaker/DIIID/DIIID_mesh_ex.ipynb
  src/examples/TokaMaker/HBT/HBT_eq_ex.ipynb
  src/examples/TokaMaker/HBT/HBT_mesh_ex.ipynb
  src/examples/TokaMaker/ITER/ITER_Hmode_ex.ipynb
  src/examples/TokaMaker/ITER/ITER_baseline_ex.ipynb
  src/examples/TokaMaker/ITER/ITER_mesh_ex.ipynb
  src/examples/TokaMaker/ITER/ITER_reconstruction_ex.ipynb
  src/examples/TokaMaker/LTX/LTX_eq_ex.ipynb
  src/examples/TokaMaker/LTX/LTX_mesh_ex.ipynb
  src/examples/TokaMaker/fixed_boundary/fixed_boundary_ex1.ipynb
  src/examples/TokaMaker/fixed_boundary/fixed_boundary_ex2.ipynb
  src/physics/grad_shaf.F90
  src/physics/grad_shaf_fit.F90
  src/physics/grad_shaf_util.F90
  src/python/OpenFUSIONToolkit/CMakeLists.txt
  src/python/OpenFUSIONToolkit/Marklin/CMakeLists.txt
  src/python/OpenFUSIONToolkit/Marklin/__init__.py
  src/python/OpenFUSIONToolkit/Marklin/_core.py
  src/python/OpenFUSIONToolkit/Marklin/_interface.py
  src/python/OpenFUSIONToolkit/ThinCurr/CMakeLists.txt
  src/python/OpenFUSIONToolkit/TokaMaker.py
  src/python/OpenFUSIONToolkit/TokaMaker/CMakeLists.txt
  src/python/OpenFUSIONToolkit/TokaMaker/__init__.py
  src/python/OpenFUSIONToolkit/TokaMaker/_core.py
  src/python/OpenFUSIONToolkit/TokaMaker/_interface.py
  src/python/OpenFUSIONToolkit/TokaMaker/meshing.py
  src/python/OpenFUSIONToolkit/TokaMaker/reconstruction.py
  src/python/OpenFUSIONToolkit/TokaMaker/util.py
  src/python/OpenFUSIONToolkit/util.py
  src/python/wrappers/tokamaker_f.F90
  src/tests/fem/CMakeLists.txt
  src/tests/grid/CMakeLists.txt
  src/tests/lin_alg/CMakeLists.txt
  src/tests/physics/CMakeLists.txt
  src/tests/physics/test_TokaMaker.py
Labels: documentation, enhancement

#60 Add native ILU0 preconditioner (local only)
  src/bin/thincurr_coupling.F90
  src/bin/thincurr_eig.F90
  src/bin/thincurr_fr.F90
  src/bin/thincurr_from_mode.F90
  src/bin/thincurr_td.F90
  src/lin_alg/oft_lu.F90
  src/lin_alg/solver_utils.F90
  src/lin_alg/superlu_bridge.c
  src/tests/lin_alg/test_native_bjacobi.F90
  src/tests/lin_alg/test_native_bjacobi.py
Labels: enhancement
