Repository OpenFUSIONToolkit/OpenFUSIONToolkit, pull requests merged in 2024-03, with the labels that each got.

#38 TokaMaker: Add support for grouping coils into coil sets
  src/bin/tokamaker_gs.F90
  src/bin/tokamaker_wall.F90
  src/docs/doc_tokamaker_main.md
  src/examples/TokaMaker/CMakeLists.txt
  src/examples/TokaMaker/HBT/HBT_eq_ex.ipynb
  src/examples/TokaMaker/HBT/HBT_geom.json
  src/examples/TokaMaker/HBT/HBT_mesh.h5
  src/examples/TokaMaker/HBT/HBT_mesh_ex.ipynb
  src/examples/TokaMaker/ITER/ITER_baseline_ex.ipynb
  src/examples/TokaMaker/ITER/ITER_mesh.h5
  src/examples/TokaMaker/ITER/ITER_mesh_ex.ipynb
  src/examples/TokaMaker/fixed_boundary/fixed_boundary_ex1.ipynb
  src/examples/TokaMaker/fixed_boundary/fixed_boundary_ex2.ipynb
  src/physics/grad_shaf.F90
  src/physics/grad_shaf_fit.F90
  src/physics/grad_shaf_td.F90
  src/physics/grad_shaf_util.F90
  src/python/OpenFUSIONToolkit/TokaMaker.py
  src/python/wrappers/tokamaker_f.F90
  src/tests/physics/test_TokaMaker.py
  src/utilities/generate_doc.py
Labels: enhancement

#41 Updated add_rectangle in Tokamaker.py
  src/python/OpenFUSIONToolkit/TokaMaker.py
Labels: enhancement

#43 TokaMaker: Add support for multiple time-dependent solves in a single Python kernel, fixes #42
  src/physics/grad_shaf_td.F90
  src/python/OpenFUSIONToolkit/TokaMaker.py
  src/python/wrappers/tokamaker_f.F90
Labels: bug, enhancement

#46 TokaMaker: Add support for inactive x-points outside the plasma region
  src/examples/TokaMaker/HBT/HBT_eq_ex.ipynb
  src/examples/TokaMaker/HBT/HBT_mesh.h5
  src/examples/TokaMaker/HBT/HBT_mesh_ex.ipynb
  src/examples/TokaMaker/ITER/ITER_baseline_ex.ipynb
  src/examples/TokaMaker/ITER/ITER_mesh.h5
  src/examples/TokaMaker/ITER/ITER_mesh_ex.ipynb
  src/examples/TokaMaker/fixed_boundary/fixed_boundary_ex1.ipynb
  src/examples/TokaMaker/fixed_boundary/fixed_boundary_ex2.ipynb
  src/physics/grad_shaf.F90
  src/physics/grad_shaf_td.F90
  src/python/OpenFUSIONToolkit/TokaMaker.py
  src/python/wrappers/tokamaker_f.F90
Labels: bug, enhancement

#47 TokaMaker: Add functionality to compute currents in conducting regions
  src/physics/grad_shaf.F90
  src/python/OpenFUSIONToolkit/TokaMaker.py
  src/python/wrappers/tokamaker_f.F90
Labels: enhancement

#49 TokaMaker: Add support for plasma row/column in mutual inductance matrix from Tok…
  src/physics/grad_shaf.F90
  src/python/wrappers/tokamaker_f.F90
  src/tests/physics/test_TokaMaker.py
Labels: enhancement

#50 Add Python interface to code coverage
  .github/workflows/cov_build.yaml
  src/tests/CMakeLists.txt
Labels: tests

#48 Add DIII-D example for TokaMaker
  src/examples/TokaMaker/CMakeLists.txt
  src/examples/TokaMaker/DIIID/DIIID_baseline_ex.ipynb
  src/examples/TokaMaker/DIIID/DIIID_geom.json
  src/examples/TokaMaker/DIIID/DIIID_mesh.h5
  src/examples/TokaMaker/DIIID/DIIID_mesh_ex.ipynb
  src/examples/TokaMaker/DIIID/g192185.02440
Labels: documentation, enhancement
